### ISSUE TITLE
升级0.0.2版本后，网易云打不开卡初始界面

### ISSUE THREAD

**Issue by xiaosi004** [BetterNCM/LogCleaner#1]
**升级0.0.2版本后，网易云打不开卡这个界面**
![image](https://github.com/BetterNCM/LogCleaner/assets/116878905/8c49339a-d554-4c26-ad2a-761259edf7e5)

- 网易云版本![image](https://github.com/BetterNCM/LogCleaner/assets/116878905/613baa84-c766-46cb-b9bc-a3dedd9fc84b)

- 电脑信息

![image](https://github.com/BetterNCM/LogCleaner/assets/116878905/5c096e86-b8ea-4693-bc47-7374796e7aac)
![image](https://github.com/BetterNCM/LogCleaner/assets/116878905/44e5208e-5b94-4890-91ce-ac28c3eb73c2)

**Comment by Nana7miChiaKi** [comment]
same，你可以去插件文件夹里把这个删了，等作者更新

**Comment by jieran233** [comment]
same

**Comment by std-microblock** [comment]
fixed
