### ISSUE TITLE
0.0.4版本和BGEnhanced（0.3.6）插件存在兼容性问题

### ISSUE THREAD

**Issue by FeiLingshu** [BetterNCM/LogCleaner#2]
0.0.4版本更新后，同时启用日志拦截和BGEnhanced插件（已是最新），会导致BGEnhanced插件无法加载，并且BGEnhanced插件的配置界面一片空白，关闭日志拦截并重载插件后BGEnhanced插件功能恢复正常。

**Comment by std-microblock** [comment]
无法复现，可以发一下F12控制台日志吗

**Comment by FeiLingshu** [comment]
启用两个插件并执行一次重新启动后的日志文件已打包至蓝奏云（https://wwme.lanzouq.com/ijvxG177rrlg）

已安装的插件：
- PluginMarket（自带）
- BGEnhanced
- 明/暗主题切换器
- LogCleaner
- MoTheme
- RoundCornerNCM（由于暂未升级win11已被手动禁用）
- StylesheetLoader（自带）
- TinyNCM
- 可视化听歌排行
- FluentMusicCover
- ListScrollFix
- 纯净分享链接
- RevivesSource

更新：
移除其他插件只保留两个目标插件和三个运行必要插件（两个自带和明/暗主题切换器），故障依旧，新的日志文件（https://wwme.lanzouq.com/iaTwh177sqrc）

**Comment by FeiLingshu** [comment]
我自己折腾了一下，确实无法复现，我回滚了一下插件代码，发现应该不是更新的锅，现在我回滚到更新之前的代码也依然会出现这个问题，看起来不是系统文件有损坏就是程序本身的文件有损坏。

> 反正最近也要更新win11了，就先这样吧，装了新系统应该就没问题了。如果作者有时间可以帮忙看看日志哪里有问题，找不到也没事，反正不影响正常使用

**Comment by std-microblock** [comment]
已经修复了哦 忘记close了

**Comment by FeiLingshu** [comment]
> **可以正常使用了，感谢作者，辛苦了**
